### ISSUE TITLE
Confusion between dependency groups and extras

### ISSUE THREAD

**Issue by EliahKagan** [Jflick58/wasm_exec#17]
Thank you for making this library!

I have noticed that, in the [quick start](https://github.com/Jflick58/wasm_exec/blob/main/.github/CONTRIBUTING.md#-quick-start) installation instructions, the `poetry install -E all` command is not correct for this project, and always fails when run, with the error message:

```text
Extra [all] is not specified.
```

This points to what I think is a deeper issue in the way the project's dependencies are specified. **I've proposed a fix in #18**.

`poetry` does not treat `all` specially. Passing `-E all` only works in a project that explicitly defines an extra whose name is literally `all`. The `--all-extras` flag installs all extras, and replacing `-E all` with `--all-extras` makes the command succeed. But that change would not, by itself, be sufficient, because `pyproject.toml` does not currently define any extras. It defines dependency groups, some of which are marked optional. [Dependency groups](https://python-poetry.org/docs/master/managing-dependencies/#dependency-groups) and [extras](https://python-poetry.org/docs/master/pyproject#extras) are separate, independent features.

There is more than one way to fix this. The approach I recommend (and have opened #18 for), which I believe achieves all the intended benefits while avoiding excess complexity, is:

- Change the command given in the quick start instructions to `poetry install --all-extras`.
- Convert the `install_wasm` dependency group into an `install-wasm` extra, since it is intended to be installable with `pip`. The dependencies it specifies--currently just `requests`--are intended to be usable even outside a development setting, so it should be an extra rather than a dependency group.
- Make the remaining optional dependency group, `test`, non-optional. Dependency groups, other than the implicit `main` dependency group, are only installable by `poetry`. They are never made available when installing the package with `pip`. The use case where the `test` group would not be wanted in local development is marginal, and the instructions for interactive local development should be kept as simple as possible.
- In the GitHub Actions workflows, use `--only=main,X` instead of `--with X` (where `X` is a dependency group). This avoids installing extra dependency groups on CI, while keeping them non-optional so `poetry` installs them automatically when simple commands like `poetry install` or `poetry install --all-extras` are used.
- *Possibly* expand `README.md` to note that the WASM runtime downloading functionality requires the `install-wasm` extra, which is included if the package is installed by `pip install 'wasm_exec[install-wasm]'`. But maybe that should not be done yet, because the code in `wasm_runtime.py` is not yet under test, and most users would only want to use the vendored runtime.

**Comment by Jflick58** [comment]
Thank you for catching this! I’m away from my computer tonight so I just wanted to drop comment acknowledging the issue and PR and let you know that I’ll review tomorrow.

**Comment by EliahKagan** [comment]
I should mention that an alternative approach could be to use *only* extras, with each dependency group becoming an extra. I believe this is fairly uncommon in projects that use `poetry`. But it's common and works fine in projects that use `setuptools`, where no separate notion of dependency groups exists, and there's no reason it can't be done in a `poetry` project. (#18 could be modified in this way if desired.)
